services:
  db:
    image: "postgres:latest"
    container_name: db_oportune
    env_file:
      - .env.db.local

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oportune_network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_oportune
    env_file:
      - ./backend/.env
    
    depends_on:
      db:
        condition: service_healthy
    
    networks:
      - oportune_network

  go-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    container_name: go_service_oportune
    env_file:
      - ./email-service/.env
          
    networks:
      - oportune_network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_oportune
    
    networks:
      - oportune_network

  # Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_oportune
    ports:
      - "8080:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - oportune_network

volumes:
  postgres_data:

networks:
  oportune_network:
    driver: bridge