name: CI

on:
  push:
    branches:
      - main
    paths:
      - backend/**/*
  pull_request:
    branches:
      - main
    paths:
      - backend/**/*

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  lint:
    name: Lint Backend
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Run ESLint
        run: npx eslint .

  test:
    name: Testes do Backend
    needs: [setup, lint]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Run Tests
        run: npm run test
